- name: Deploy to Kubernetes
  hosts: localhost
  tasks:
    - name: Create ConfigMap
      kubernetes.core.k8s:
        state: present
        src: kubernetes/backend.yaml
        namespace: default
        kind: ConfigMap

    - name: Create Deployment
      kubernetes.core.k8s:
        state: present  
        src: kubernetes/backend.yaml
        namespace: default
        kind: Deployment

    - name: Create Service
      kubernetes.core.k8s:
        state: present
        src: kubernetes/backend.yaml
        namespace: default
        kind: Service