---
- hosts: localhost
  become: yes
  vars:
    ansible_user: veerendra
    ansible_ssh_pass: veerendra
  tasks:
    - name: Apply Kubernetes frontend manifest
      kubectl:
        binary_insecure_skip_tls_verify: true
        filename: kubernetes/frontend.yaml
        state: present