---
- name: Deploy chat app to minikube
  hosts: localhost
  tasks:
    # - name: Database Configurations Setup
    #   kubernetes.core.k8s:
    #     kubeconfig: /etc/ansible/config
    #     state: present
    #     definition: "{{ lookup('template', '../kubernates/backend.yaml') }}"
    - name: Create Kubernetes manifests
      template:
        src: kubernetes/backend.yaml
        dest: ./backend.yaml

    - name: Apply Kubernetes manifests
      command: kubectl apply -f ./deployment.yml --validate=false

    # - name: apply elasticsearch
    #   shell: kubectl apply -f ../kubernetes/elasticsearch.yaml

    # - name: apply logstash
    #   shell: kubectl apply -f ../kubernetes/logstash.yaml

    # - name: apply kibana
    #   shell: kubectl apply -f ../kubernetes/kibana.yaml

    # - name: apply filebeat
    #   shell: kubectl apply -f ../kubernetes/filebeat.yaml